# Generated by Django 4.2.4 on 2023-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, verbose_name='IMYA')),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
